// Bundles the files in data/ into src/data.generated.ts so the core package
// works the same in the browser, in Node and in tests (no file access needed).
//
//   npm run gen -w @bvs/core
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = join(root, "data");

// Versions we have verified verse-count data for, keyed by YouVersion bible id.
const BUILTIN = [
  { abbr: "AMP", bibleId: 1588, language: "en", title: "Amplified Bible" },
  { abbr: "NIV", bibleId: 111, language: "en", title: "New International Version" },
  { abbr: "LSG", bibleId: 93, language: "fr", title: "Louis Segond 1910" },
  { abbr: "S21", bibleId: 152, language: "fr", title: "Segond 21" },
];
const idOf = Object.fromEntries(BUILTIN.map((v) => [v.abbr, v.bibleId]));

const knownByAbbr = JSON.parse(readFileSync(join(data, "known_counts.json"), "utf8"));
const knownCounts = {};
for (const [abbr, counts] of Object.entries(knownByAbbr)) {
  if (!(abbr in idOf)) throw new Error(`known_counts.json: unknown version ${abbr}`);
  knownCounts[idOf[abbr]] = counts;
}

const overrides = {};
for (const file of readdirSync(join(data, "overrides")).sort()) {
  const abbr = file.replace(/\.map$/, "");
  if (!(abbr in idOf)) throw new Error(`overrides/${file}: unknown version ${abbr}`);
  overrides[idOf[abbr]] = readFileSync(join(data, "overrides", file), "utf8");
}

const out = `// Generated by scripts/gen-data.mjs from data/ - do not edit by hand.
/* eslint-disable */

/** Paratext versification files from SIL libpalaso (MIT licence). */
export const ENG_VRS: string = ${JSON.stringify(readFileSync(join(data, "eng.vrs"), "utf8"))};
export const ORG_VRS: string = ${JSON.stringify(readFileSync(join(data, "org.vrs"), "utf8"))};

export interface BuiltinVersion {
  abbr: string;
  bibleId: number;
  language: string;
  title: string;
}

export const BUILTIN_VERSIONS: BuiltinVersion[] = ${JSON.stringify(BUILTIN, null, 2)};

/**
 * Real verse counts (bible.com, Sept 2026) for every chapter where a version
 * differs from English numbering or English and Hebrew numbering differ.
 * All other chapters have the same count in both systems.
 * { bibleId: { "BOOK.chapter": verseCount } }
 */
export const KNOWN_COUNTS: Record<number, Record<string, number>> = ${JSON.stringify(knownCounts)};

/** Hand-checked correction tables (data/overrides/*.map), keyed by bible id. */
export const OVERRIDES: Record<number, string> = ${JSON.stringify(overrides, null, 2)};
`;
writeFileSync(join(root, "src", "data.generated.ts"), out);
console.log("wrote src/data.generated.ts");
