// Bundles the files in data/ into src/data.generated.ts so the core package
// works the same in the browser, in Node and in tests (no file access needed).
//
//   npm run gen -w @bvs/core
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { VERIFIED } from "./verified.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = join(root, "data");
const read = (...path) => readFileSync(join(data, ...path), "utf8");

// Everything here is keyed by bible id: abbreviations aren't unique (ARC is
// both 212 and 3407), and the ones users type are their own.
const BIBLE_ID = /^[1-9]\d*$/;
const CHAPTER = /^[0-9A-Z]{3}\.[1-9]\d*$/;
const knownCounts = {};
for (const [id, counts] of Object.entries(JSON.parse(read("known_counts.json")))) {
  if (!BIBLE_ID.test(id)) throw new Error(`known_counts.json: key ${id} is not a bible id`);
  for (const [ch, n] of Object.entries(counts)) {
    if (!CHAPTER.test(ch) || !Number.isInteger(n) || n < 0) throw new Error(`known_counts.json: ${id} ${ch}: ${n}`);
  }
  knownCounts[id] = counts;
}
for (const v of VERIFIED) {
  if (!(v.bibleId in knownCounts)) throw new Error(`${v.abbr} (${v.bibleId}) is verified but has no counts`);
}

const overrides = {};
for (const file of readdirSync(join(data, "overrides")).sort()) {
  const id = file.replace(/\.map$/, "");
  if (!BIBLE_ID.test(id)) throw new Error(`overrides/${file}: name it <bible id>.map`);
  if (!(id in knownCounts)) throw new Error(`overrides/${file}: no counts for bible ${id}`);
  overrides[id] = read("overrides", file);
}

// YouVersion's numbering label per bible id, which the official API doesn't
// expose (see scripts/import-survey.mjs).
const SCHEMES = ["eng", "org", "rso", "rsc", "lxx", "vul"];
const labels = JSON.parse(read("labels.json"));
for (const [id, vrs] of Object.entries(labels)) {
  if (!BIBLE_ID.test(id) || !SCHEMES.includes(vrs)) throw new Error(`labels.json: ${id}: ${vrs}`);
}
const vrs = (name) => JSON.stringify(read(`${name}.vrs`));

const out = `// Generated by scripts/gen-data.mjs from data/ - do not edit by hand.
/* eslint-disable */

/** Paratext versification files from SIL libpalaso (MIT licence). */
export const ENG_VRS: string = ${vrs("eng")};
export const ORG_VRS: string = ${vrs("org")};
/** Russian Synodal (Orthodox and Protestant editions), Septuagint, Vulgate. */
export const RSO_VRS: string = ${vrs("rso")};
export const RSC_VRS: string = ${vrs("rsc")};
export const LXX_VRS: string = ${vrs("lxx")};
export const VUL_VRS: string = ${vrs("vul")};

/**
 * YouVersion's numbering label (\`vrs\`) by bible id, from bible.com (Sept 2026).
 * Versions not listed are unlabelled or weren't surveyed.
 */
export const VRS_LABELS: Record<number, "eng" | "org" | "rso" | "rsc" | "lxx" | "vul"> = ${JSON.stringify(labels)};

/** A version whose numbering was checked by hand, chapter by chapter. */
export interface VerifiedVersion {
  abbr: string;
  bibleId: number;
  language: string;
  title: string;
}

export const VERIFIED_VERSIONS: VerifiedVersion[] = ${JSON.stringify(VERIFIED, null, 2)};

/**
 * Real verse counts (bible.com, Sept 2026) of the verified versions and the
 * others scanned for the versification survey, for every chapter where a
 * version differs from English numbering or where its candidate systems
 * disagree. Every other chapter has the count the engine would infer.
 * 0 is a chapter the version doesn't have.
 * { bibleId: { "BOOK.chapter": verseCount } }
 */
export const KNOWN_COUNTS: Record<number, Record<string, number>> = ${JSON.stringify(knownCounts)};

/** Hand-checked correction tables (data/overrides/*.map), keyed by bible id. */
export const OVERRIDES: Record<number, string> = ${JSON.stringify(overrides, null, 2)};
`;
writeFileSync(join(root, "src", "data.generated.ts"), out);
console.log("wrote src/data.generated.ts");
