// Bundles the files in data/ into src/data.generated.ts so the core package
// works the same in the browser, in Node and in tests (no file access needed).
//
//   npm run gen -w @bvs/core
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = join(root, "data");
// The Synodal, Septuagint and Vulgate files and YouVersion's numbering labels
// live with the versification survey that collected them; read them from
// there rather than keep a second copy.
const survey = join(root, "..", "..", "tools", "versification-survey");

// Versions we have verified verse-count data for, keyed by YouVersion bible id.
const BUILTIN = [
  { abbr: "AMP", bibleId: 1588, language: "en", title: "Amplified Bible" },
  { abbr: "NIV", bibleId: 111, language: "en", title: "New International Version" },
  { abbr: "LSG", bibleId: 93, language: "fr", title: "Louis Segond 1910" },
  { abbr: "S21", bibleId: 152, language: "fr", title: "Segond 21" },
];
const idOf = Object.fromEntries(BUILTIN.map((v) => [v.abbr, v.bibleId]));

const knownByAbbr = JSON.parse(readFileSync(join(data, "known_counts.json"), "utf8"));
const knownCounts = {};
for (const [abbr, counts] of Object.entries(knownByAbbr)) {
  if (!(abbr in idOf)) throw new Error(`known_counts.json: unknown version ${abbr}`);
  knownCounts[idOf[abbr]] = counts;
}

const overrides = {};
for (const file of readdirSync(join(data, "overrides")).sort()) {
  const abbr = file.replace(/\.map$/, "");
  if (!(abbr in idOf)) throw new Error(`overrides/${file}: unknown version ${abbr}`);
  overrides[idOf[abbr]] = readFileSync(join(data, "overrides", file), "utf8");
}

// YouVersion's numbering label per bible id: the scanned versions plus every
// labelled candidate. The official API doesn't expose it.
const SCHEMES = ["eng", "org", "rso", "rsc", "lxx", "vul"];
const labels = {};
const addLabel = (id, vrs, from) => {
  if (!vrs) return;
  if (!SCHEMES.includes(vrs)) throw new Error(`${from}: unknown numbering ${vrs} for ${id}`);
  if (labels[id] && labels[id] !== vrs) throw new Error(`${from}: ${id} is both ${labels[id]} and ${vrs}`);
  labels[id] = vrs;
};
const scanned = JSON.parse(readFileSync(join(survey, "data", "counts.json"), "utf8"));
for (const [id, v] of Object.entries(scanned)) addLabel(Number(id), v.vrs, "counts.json");
const candidates = JSON.parse(readFileSync(join(survey, "data", "candidates.json"), "utf8"));
for (const versions of Object.values(candidates)) {
  for (const v of versions) addLabel(v.id, v.vrs, "candidates.json");
}
const sortedLabels = Object.fromEntries(Object.entries(labels).sort(([a], [b]) => Number(a) - Number(b)));
const vrs = (name) => JSON.stringify(readFileSync(join(survey, "vrs", `${name}.vrs`), "utf8"));

const out = `// Generated by scripts/gen-data.mjs from data/ - do not edit by hand.
/* eslint-disable */

/** Paratext versification files from SIL libpalaso (MIT licence). */
export const ENG_VRS: string = ${JSON.stringify(readFileSync(join(data, "eng.vrs"), "utf8"))};
export const ORG_VRS: string = ${JSON.stringify(readFileSync(join(data, "org.vrs"), "utf8"))};
/** Russian Synodal (Orthodox and Protestant editions), Septuagint, Vulgate. */
export const RSO_VRS: string = ${vrs("rso")};
export const RSC_VRS: string = ${vrs("rsc")};
export const LXX_VRS: string = ${vrs("lxx")};
export const VUL_VRS: string = ${vrs("vul")};

/**
 * YouVersion's numbering label (\`vrs\`) by bible id, from bible.com (Sept 2026).
 * Versions not listed are unlabelled or weren't surveyed.
 */
export const VRS_LABELS: Record<number, "eng" | "org" | "rso" | "rsc" | "lxx" | "vul"> = ${JSON.stringify(sortedLabels)};

export interface BuiltinVersion {
  abbr: string;
  bibleId: number;
  language: string;
  title: string;
}

export const BUILTIN_VERSIONS: BuiltinVersion[] = ${JSON.stringify(BUILTIN, null, 2)};

/**
 * Real verse counts (bible.com, Sept 2026) for every chapter where a version
 * differs from English numbering or English and Hebrew numbering differ.
 * All other chapters have the same count in both systems.
 * { bibleId: { "BOOK.chapter": verseCount } }
 */
export const KNOWN_COUNTS: Record<number, Record<string, number>> = ${JSON.stringify(knownCounts)};

/** Hand-checked correction tables (data/overrides/*.map), keyed by bible id. */
export const OVERRIDES: Record<number, string> = ${JSON.stringify(overrides, null, 2)};
`;
writeFileSync(join(root, "src", "data.generated.ts"), out);
console.log("wrote src/data.generated.ts");
