// The most used versions of 20 big languages, most used first. YouVersion
// publishes no ranking, so this is judgement: English follows the ECPA/Circana
// bestseller lists, the others what those languages' churches mostly read
// (Union in Chinese and Swahili, Synodal in Russian, Van Dyck in Arabic,
// Cornilescu in Romanian…), among the versions YouVersion has. Each list
// includes the version bible.com opens for the language (data/defaults.json);
// a default a list leaves out ranks just after it. Ranks every version of a language in the
// scan for the person's versions (versionRank); gen-data checks each `abbr`
// against the bundled name, like verified.mjs.
export const POPULAR = {
  en: [
    { abbr: "NIV", bibleId: 111 },
    { abbr: "KJV", bibleId: 1 },
    { abbr: "ESV", bibleId: 59 },
    { abbr: "NLT", bibleId: 116 },
    { abbr: "NKJV", bibleId: 114 },
    { abbr: "CSB", bibleId: 1713 },
    { abbr: "AMP", bibleId: 1588 },
    { abbr: "NASB2020", bibleId: 2692 },
    { abbr: "NASB1995", bibleId: 100 },
    { abbr: "MSG", bibleId: 97 },
    { abbr: "NIrV", bibleId: 110 },
    { abbr: "CEV", bibleId: 392 },
    { abbr: "GNT", bibleId: 68 },
    { abbr: "NET", bibleId: 107 },
  ],
  es: [
    { abbr: "RVR1960", bibleId: 149 },
    { abbr: "NVI", bibleId: 128 },
    { abbr: "NTV", bibleId: 127 },
    { abbr: "LBLA", bibleId: 89 },
    { abbr: "NBLA", bibleId: 103 },
    { abbr: "DHH94I", bibleId: 52 },
    { abbr: "RVC", bibleId: 146 },
    { abbr: "TLA", bibleId: 176 },
    { abbr: "PDT", bibleId: 197 },
    { abbr: "NVI", bibleId: 1637 },
  ],
  pt: [
    { abbr: "NVI", bibleId: 129 },
    { abbr: "ARC", bibleId: 212 },
    { abbr: "ARA", bibleId: 1608 },
    { abbr: "NVT", bibleId: 1930 },
    { abbr: "NAA", bibleId: 1840 },
    { abbr: "NTLH", bibleId: 211 },
    { abbr: "A21", bibleId: 2645 },
  ],
  fr: [
    { abbr: "LSG", bibleId: 93 },
    { abbr: "S21", bibleId: 152 },
    { abbr: "BDS", bibleId: 21 },
    { abbr: "NEG79", bibleId: 106 },
    { abbr: "PDV2017", bibleId: 133 },
    { abbr: "NBS", bibleId: 104 },
    { abbr: "BFC", bibleId: 63 },
  ],
  de: [
    { abbr: "DELUT", bibleId: 51 },
    { abbr: "SCH2000", bibleId: 157 },
    { abbr: "Hfa", bibleId: 73 },
    { abbr: "NGU2011", bibleId: 108 },
    { abbr: "ELB", bibleId: 57 },
  ],
  zh: [
    { abbr: "CUNPSS-神", bibleId: 48 },
    { abbr: "CUNP-神", bibleId: 46 },
    { abbr: "RCUVSS", bibleId: 140 },
    { abbr: "RCUV", bibleId: 139 },
    { abbr: "CCB", bibleId: 36 },
    { abbr: "CCB", bibleId: 1392 },
    { abbr: "CNVS", bibleId: 41 },
    { abbr: "CNV", bibleId: 40 },
    { abbr: "CSBS", bibleId: 43 },
    { abbr: "CUVMPS", bibleId: 4804 },
  ],
  ko: [
    { abbr: "KRV", bibleId: 88 },
    { abbr: "RNKSV", bibleId: 142 },
    { abbr: "KLB", bibleId: 86 },
    { abbr: "KOERV", bibleId: 3803 },
    { abbr: "WB", bibleId: 4639 },
  ],
  ja: [
    { abbr: "新共同訳", bibleId: 1819 },
    { abbr: "NJB", bibleId: 4869 },
    { abbr: "口語訳", bibleId: 1820 },
    { abbr: "JCB", bibleId: 83 },
    { abbr: "JA1955", bibleId: 81 },
  ],
  ru: [
    { abbr: "SYNO", bibleId: 400 },
    { abbr: "Синод", bibleId: 167 },
    { abbr: "НРП", bibleId: 143 },
    { abbr: "RSP", bibleId: 201 },
    { abbr: "CARS", bibleId: 385 },
    { abbr: "BTI", bibleId: 313 },
  ],
  uk: [
    { abbr: "UBIO", bibleId: 186 },
    { abbr: "НПУ", bibleId: 3269 },
    { abbr: "UMT", bibleId: 204 },
    { abbr: "UKRK", bibleId: 188 },
    { abbr: "УТТ", bibleId: 1755 },
  ],
  ar: [
    { abbr: "AVD", bibleId: 13 },
    { abbr: "KEH", bibleId: 101 },
    { abbr: "GNA2025", bibleId: 67 },
    { abbr: "ت ع م", bibleId: 195 },
    { abbr: "SAB", bibleId: 153 },
  ],
  hi: [
    { abbr: "HHBD", bibleId: 819 },
    { abbr: "HCV", bibleId: 1628 },
    { abbr: "HERV", bibleId: 2562 },
    { abbr: "IRVHin", bibleId: 1980 },
    { abbr: "HINOVBSI", bibleId: 1683 },
  ],
  id: [
    { abbr: "TB", bibleId: 306 },
    { abbr: "BIMK", bibleId: 27 },
    { abbr: "FAYH", bibleId: 2727 },
    { abbr: "AMD", bibleId: 199 },
    { abbr: "TSI", bibleId: 320 },
  ],
  fil: [
    { abbr: "TLAB", bibleId: 177 },
    { abbr: "ASD", bibleId: 1264 },
    { abbr: "MBB05", bibleId: 144 },
    { abbr: "ABTAG01", bibleId: 2195 },
    { abbr: "RTPV05", bibleId: 399 },
  ],
  sw: [
    { abbr: "SUV", bibleId: 164 },
    { abbr: "NEN", bibleId: 1627 },
    { abbr: "BHN", bibleId: 74 },
    { abbr: "SRUV", bibleId: 1818 },
    { abbr: "NENO", bibleId: 4369 },
  ],
  it: [
    { abbr: "NR06", bibleId: 122 },
    { abbr: "NR2006", bibleId: 4833 },
    { abbr: "NR94", bibleId: 123 },
    { abbr: "RDV24", bibleId: 141 },
    { abbr: "ICL00D", bibleId: 1196 },
    { abbr: "IRB20", bibleId: 3368 },
  ],
  pl: [
    { abbr: "BW1975", bibleId: 3490 },
    { abbr: "UBG", bibleId: 138 },
    { abbr: "SNP", bibleId: 2095 },
    { abbr: "PBG", bibleId: 132 },
    { abbr: "NBG", bibleId: 319 },
    { abbr: "PLNT", bibleId: 137 },
  ],
  ro: [
    { abbr: "VDC", bibleId: 191 },
    { abbr: "NTR", bibleId: 126 },
    { abbr: "EDCR", bibleId: 2311 },
    { abbr: "BTF2015", bibleId: 903 },
    { abbr: "VDCL", bibleId: 1996 },
  ],
  nl: [
    { abbr: "HSV", bibleId: 1990 },
    { abbr: "NBG51", bibleId: 328 },
    { abbr: "HTB", bibleId: 75 },
    { abbr: "BB", bibleId: 1276 },
    { abbr: "STV", bibleId: 165 },
  ],
  vi: [
    { abbr: "VIE1925", bibleId: 193 },
    { abbr: "VIE2010", bibleId: 151 },
    { abbr: "BD2011", bibleId: 19 },
    { abbr: "KTHD", bibleId: 1638 },
    { abbr: "NVB", bibleId: 449 },
    { abbr: "BPT", bibleId: 205 },
  ],
};
