// Versions whose numbering was checked by hand, chapter by chapter. Every other
// version in data/known_counts.json has scanned counts only. Read by
// gen-data.mjs (the app's VERIFIED_VERSIONS) and import-survey.mjs. Names come
// from data/names.json like any other version's; `abbr` is only for reading
// this list, and gen-data checks it against the bundled name.
export const VERIFIED = [
  { abbr: "AMP", bibleId: 1588 },
  { abbr: "NIV", bibleId: 111 },
  { abbr: "LSG", bibleId: 93 },
  { abbr: "S21", bibleId: 152 },
  // Checked the same way against NIV and LSG (Sept 2026): the two most used
  // versions of each language in popular.mjs, the two most used of each
  // numbering label (rsc: НРП, RSP; vul: DRC1752, CPDV), and NCV.
  { abbr: "KJV", bibleId: 1 },
  { abbr: "RVR1960", bibleId: 149 },
  { abbr: "NVI", bibleId: 128 },
  { abbr: "NVI", bibleId: 129 },
  { abbr: "ARC", bibleId: 212 },
  { abbr: "DELUT", bibleId: 51 },
  { abbr: "SCH2000", bibleId: 157 },
  { abbr: "CUNPSS-神", bibleId: 48 },
  { abbr: "CUNP-神", bibleId: 46 },
  { abbr: "KRV", bibleId: 88 },
  { abbr: "RNKSV", bibleId: 142 },
  { abbr: "新共同訳", bibleId: 1819 },
  { abbr: "NJB", bibleId: 4869 },
  { abbr: "SYNO", bibleId: 400 },
  { abbr: "Синод", bibleId: 167 },
  { abbr: "UBIO", bibleId: 186 },
  { abbr: "НПУ", bibleId: 3269 },
  { abbr: "AVD", bibleId: 13 },
  { abbr: "KEH", bibleId: 101 },
  { abbr: "HHBD", bibleId: 819 },
  { abbr: "HCV", bibleId: 1628 },
  { abbr: "TB", bibleId: 306 },
  { abbr: "BIMK", bibleId: 27 },
  { abbr: "TLAB", bibleId: 177 },
  { abbr: "ASD", bibleId: 1264 },
  { abbr: "SUV", bibleId: 164 },
  { abbr: "NEN", bibleId: 1627 },
  { abbr: "NR06", bibleId: 122 },
  { abbr: "NR2006", bibleId: 4833 },
  { abbr: "BW1975", bibleId: 3490 },
  { abbr: "UBG", bibleId: 138 },
  { abbr: "VDC", bibleId: 191 },
  { abbr: "NTR", bibleId: 126 },
  { abbr: "HSV", bibleId: 1990 },
  { abbr: "NBG51", bibleId: 328 },
  { abbr: "VIE1925", bibleId: 193 },
  { abbr: "VIE2010", bibleId: 151 },
  { abbr: "НРП", bibleId: 143 },
  { abbr: "RSP", bibleId: 201 },
  { abbr: "DRC1752", bibleId: 55 },
  { abbr: "CPDV", bibleId: 42 },
  { abbr: "NCV", bibleId: 105 },
];
